### ISSUE TITLE
Breaking changes for new major version?

### ISSUE THREAD

**Issue by lukehaas** [Shakeskeyboarde/slashes#5]
I noticed a new major version of this library was released recently but I'm not seeing any changelog or release notes to say what those changes are. Given that it's a major release presumably there are breaking changes?

**Comment by Shakeskeyboarde** [comment]
Breaking Changes:

- `addSlashes` no longer escapes backslashes by default, because `\'` is not valid escape sequence in JSON.
- `addSlashes` escapes null characters to `\u0000`, because `\0` is not a valid escape sequence in JSON.
- `addSlashes` no longer accepts a `count` option.
- `addSlashes` escape sequence options (`characters`, `escapeNonAscii`) have been replaced with a `getEscaped` callback option.
- `stripSlashes` has been renamed to `removeSlashes`.
- `removeSlashes` no longer accepts a `count` option.
- `removeSlashes` escape sequence options (`defaultEscapeValue`, `b`, `f`, `n`, `r`, `t`, `v`, `0`, `x`, `u`, `uEs6`) have been replaced with a `getUnescaped` callback option.
- `removeSlashes` now handles octal escapes.
